[project]
name = "pkr"
version = "0.1.0"
description = "Poker training software."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.6",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.1.1",
]
