# Generated by Django 5.2.6 on 2025-09-30 14:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PreFlopRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("entries", models.JSONField(default=dict)),
                (
                    "positions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        default=list,
                        size=None,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Preflop Range",
                "verbose_name_plural": "Preflop Ranges",
            },
        ),
    ]
