# Generated by Django 5.2.6 on 2025-10-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranges", "0001_create_preflop_range_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="prefloprange",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
