name: Run Linters

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Create .env.mk file
        run: touch .env.mk

      - name: Run linters via Makefile
        run: make dlint
